package mybatis.dao;

import java.util.List;
import mybatis.model.Flashcardpack;
import org.mybatis.cdi.Mapper;

@Mapper
public interface FlashcardpackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.flashcardpack
     *
     * @mbg.generated Fri Mar 21 16:28:48 EET 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.flashcardpack
     *
     * @mbg.generated Fri Mar 21 16:28:48 EET 2025
     */
    int insert(Flashcardpack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.flashcardpack
     *
     * @mbg.generated Fri Mar 21 16:28:48 EET 2025
     */
    Flashcardpack selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.flashcardpack
     *
     * @mbg.generated Fri Mar 21 16:28:48 EET 2025
     */
    List<Flashcardpack> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.flashcardpack
     *
     * @mbg.generated Fri Mar 21 16:28:48 EET 2025
     */
    int updateByPrimaryKey(Flashcardpack record);
}