package mybatis.model;


public class Flashcardpack {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.flashcardpack.id
     *
     * @mbg.generated Fri Mar 21 16:28:48 EET 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.flashcardpack.name
     *
     * @mbg.generated Fri Mar 21 16:28:48 EET 2025
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.flashcardpack.id
     *
     * @return the value of public.flashcardpack.id
     *
     * @mbg.generated Fri Mar 21 16:28:48 EET 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.flashcardpack.id
     *
     * @param id the value for public.flashcardpack.id
     *
     * @mbg.generated Fri Mar 21 16:28:48 EET 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.flashcardpack.name
     *
     * @return the value of public.flashcardpack.name
     *
     * @mbg.generated Fri Mar 21 16:28:48 EET 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.flashcardpack.name
     *
     * @param name the value for public.flashcardpack.name
     *
     * @mbg.generated Fri Mar 21 16:28:48 EET 2025
     */
    public void setName(String name) {
        this.name = name;
    }
}